stages:
  - build

############################
# BACKEND MACOS
############################
build:backend:macos:
  stage: build
  tags:
    - shell

  script:
    - scripts/build/backendMacOs.sh

  artifacts:
    expire_in: 1 day
    paths:
      - backend/dist/mac/nadia-backend

############################
# DESKTOP (Electron build only, no packaging)
############################
build:desktop:
  stage: build
  image: node:22-bullseye

  script:
    - scripts/build/desktop.sh

  artifacts:
    expire_in: 1 day
    paths:
      - desktop/dist
