# A ranger dans scripts pour mettre au propre plus tard
package:windows:
  stage: package
  image: electronuserland/builder:wine-mono

  needs:
    - job: build
      artifacts: true

  variables:
    ELECTRON_CACHE: "$CI_PROJECT_DIR/.cache/electron"
    ELECTRON_BUILDER_CACHE: "$CI_PROJECT_DIR/.cache/electron-builder"
    ELECTRON_BUILDER_DISABLE_RCEDit: "true"

  script:
    - cd desktop
    - npm install --ignore-scripts
    - npx electron-builder --win --x64 --publish=never

  artifacts:
    name: "nadia-windows"
    expire_in: 7 days
    paths:
      - desktop/dist/*.exe

package:macos:
  stage: package
  tags:
    - shell

  needs:
    - job: build
      artifacts: true

  before_script:
    - 'export NVM_DIR="$HOME/.nvm"'
    - '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'
    - nvm use 22
    - node --version
    - npm --version

  script:
    - export APPLE_API_KEY_ID="385MGD36L7" # a deplacer dans les variables CI
    - export APPLE_API_ISSUER="22737eef-efcb-4e85-bb6c-c958f5c44d75"
    - export APPLE_API_KEY_PATH="$HOME/.apple/385MGD36L7.p8"
    - cd desktop
    - npm install
    - npm run pack

  artifacts:
    name: "nadia-macos"
    expire_in: 7 days
    paths:
      - "desktop/dist/*.dmg"
