stages:
  - package

############################
# PACKAGE WINDOWS
############################
package:windows:
  stage: package
  needs:
    - build:desktop
  script:
    - scripts/package/windowsGitlab.sh

############################
# PACKAGE MACOS
############################
package:macos:
  stage: package
  tags:
    - shell

  needs:
    - build:desktop
    - build:backend:macos

  before_script:
    - scripts/setup/prePackageMacOs.sh

  script:
    - scripts/package/macos.sh

  artifacts:
    name: "nadia-macos"
    expire_in: 7 days
    paths:
      - desktop/dist/*.dmg
